apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-test
  labels:
    app: network-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-test
  template:
    metadata:
      labels:
        app: network-test
    spec:
      containers:
        - name: network-test
          image: network-test:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /api
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
