apiVersion: v1
kind: Service
metadata:
  name: network-test
  labels:
    app: network-test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: network-test
